import csv
import os

import pytest

# Artifact CSV is generated by a live scrape; skip when absent so default runs stay green.
CSV_PATH = os.path.join(os.path.dirname(__file__), os.pardir, 'ncaa', 'rosters', 'rosters_2025-26_team_291.csv')
pytestmark = pytest.mark.skipif(not os.path.exists(CSV_PATH),
                                reason="artifact CSV not generated — run: uv run wbb scrape -s 2025-26 -team 291")

def test_humboldt_team_291_academic_years_present():
    """Ensure the generated roster CSV for Cal Poly Humboldt (team 291) has academic_year values"""
    csv_path = os.path.join(os.path.dirname(__file__), os.pardir, 'ncaa', 'rosters', 'rosters_2025-26_team_291.csv')
    csv_path = os.path.abspath(csv_path)
    assert os.path.exists(csv_path), f"Missing roster CSV: {csv_path}"

    with open(csv_path, newline='') as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
        assert rows, "CSV has no rows"

        empty_years = [r for r in rows if not r.get('academic_year') or r.get('academic_year').strip() == '']
        assert not empty_years, f"Found players without academic_year: {len(empty_years)} rows"
