import csv
import os

import pytest

# Artifact CSV is generated by a live scrape; skip when absent so default runs stay green.
CSV_PATH = os.path.join(os.path.dirname(__file__), os.pardir, 'ncaa', 'rosters', 'rosters_2025-26_team_433.csv')
pytestmark = pytest.mark.skipif(not os.path.exists(CSV_PATH),
                                reason="artifact CSV not generated — run: uv run wbb scrape -s 2025-26 -team 433")

def test_olemiss_team_433_academic_years_present_and_normalized():
    """Ensure the generated roster CSV for Ole Miss (team 433) has academic_year values
    and that they don't come from the wrong "Exp" column tokens like '1L', 'TR' or 'HS'.
    """
    csv_path = os.path.join(os.path.dirname(__file__), os.pardir, 'ncaa', 'rosters', 'rosters_2025-26_team_433.csv')
    csv_path = os.path.abspath(csv_path)
    assert os.path.exists(csv_path), f"Missing roster CSV: {csv_path}"

    with open(csv_path, newline='') as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
        assert rows, "CSV has no rows"

        # Ensure academic_year is present for every player
        empty_years = [r for r in rows if not r.get('academic_year') or r.get('academic_year').strip() == '']
        assert not empty_years, f"Found players without academic_year: {len(empty_years)} rows"

        # Make sure none of the academic_year values look like the old 'Exp' tokens
        bad_tokens = {'1l', 'tr', 'hs'}
        bad_rows = [r for r in rows if r.get('academic_year') and r.get('academic_year').strip().lower() in bad_tokens]
        assert not bad_rows, f"Found players whose academic_year looks like 'Exp' values: {len(bad_rows)} rows"
