import csv
import os

import pytest

# Artifact CSV is generated by a live scrape; skip when absent so default runs stay green.
CSV_PATH = os.path.join(os.path.dirname(__file__), os.pardir, 'ncaa', 'rosters', 'rosters_2025-26_team_1050.csv')
pytestmark = pytest.mark.skipif(not os.path.exists(CSV_PATH),
                                reason="artifact CSV not generated — run: uv run wbb scrape -s 2025-26 -team 1050")

def test_defiance_team_1050_hometown_and_highschool_present():
    """Ensure the generated roster CSV for Defiance (team 1050) has hometown and high_school values"""
    csv_path = os.path.join(os.path.dirname(__file__), os.pardir, 'ncaa', 'rosters', 'rosters_2025-26_team_1050.csv')
    csv_path = os.path.abspath(csv_path)
    assert os.path.exists(csv_path), f"Missing roster CSV: {csv_path}"

    with open(csv_path, newline='') as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
        assert rows, "CSV has no rows"

        missing = [r for r in rows if (not r.get('hometown') or r.get('hometown').strip() == '') or (not r.get('high_school') or r.get('high_school').strip() == '')]
        assert not missing, f"Found players missing hometown or high_school: {len(missing)} rows"
